[package]
name = "nofio"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
log = "0.4"
mio = "0.6"
mio-extras = "2"

[dev-dependencies]
pretty_env_logger = "0.3"
